name: Development build to iOs simulator on push

on:
  push:
    branches: ['main']

jobs:
  ios-simulator-build:
    name: IOs Simulator Build
    type: build
    params:
      platform: ios
      profile: ios-simulator