name: Healthcheck

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-healthcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run healthcheck (lint, format check, tests, expo doctor)
        run: npm run healthcheck